# see: https://github.com/probot/settings

repository:
  name: template.github-action # replace
  description: Basic template repo for creating Github actions # replace
  topics: # replace
  private: false
  has_issues: false
  has_wiki: false
  is_template: true # replace
  default_branch: main
  allow_squash_merge: false
  allow_merge_commit: true
  allow_rebase_merge: false
  archived: false

teams:
  - name: engineering
    permission: admin

branches:
  - name: main
    protection:
      required_pull_request_reviews:
        required_approving_review_count: 1
        dismiss_stale_reviews: true
        require_code_owner_reviews: true
        dismissal_restrictions: {}
      required_status_checks:
        strict: true
        contexts: []
      enforce_admins: true
      restrictions:
